export const sidebarItems = [
    { iconClass: "fa-house", text: "Home" },
    { iconClass: "fa-video", text: "Shorts" },
    { iconClass: "fa-box", text: "Subscriber" },
    { iconClass: "fa-user", text: "Your Channel" },
    { iconClass: "fa-clock", text: "History" },
    { iconClass: "fa-camera", text: "Videos" },
    { iconClass: "fa-clock", text: "Watch Later" },
    { iconClass: "fa-thumbs-up", text: "Liked Videos" },
    { iconClass: "fa-stairs", text: "Trending" },
    { iconClass: "fa-cart-shopping", text: "Shopping" },
    { iconClass: "fa-music", text: "Music" },
    { iconClass: "fa-film", text: "Film" },
    { iconClass: "fa-star-of-life", text: "Live" },
    { iconClass: "fa-headset", text: "Gaming" },
    { iconClass: "fa-newspaper", text: "News" },
    { iconClass: "fa-medal", text: "Spots" },
    { iconClass: "fa-chalkboard", text: "Learnings" },
];